workflows:
  build-android:
    name: Android Build
    instance_type: mac_mini_m1
    max_build_duration: 120
    scripts:
      - flutter packages pub get
      - name: Decode Env
        script:
#         Decode environment variable and save into env.json
          echo $ENVIRONMENT_FILE | base64 --decode > env.json
          cat env.json
      - name: Build APK with Flutter
        script:
#         Build new apk using decoded environment file
          flutter build apk --release --dart-define-from-file=env.json
    artifacts:
      - build/**/outputs/**/*.apk